language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t girish527/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run girish527/react-test npm test -- --coverage

after_success:
  - docker build -t girish527/multi-client ./client
  - docker build -t girish527/multi-nginx ./nginx
  - docker build -t girish527/multi-server ./server
  - docker build -t girish527/multi-worker ./worker

  #Login into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to docker hub
  - docker push girish527/multi-client
  - docker push girish527/multi-nginx
  - docker push girish527/multi-server
  - docker push girish527/multi-worker